## Introduction

Ce rapport automatique à été produit par l'application [Shiny SBM](https://forgemia.inra.fr/theodore.vanrenterghem/shinySbm) (aussi disponible via ce [lien](https://shiny.migale.inrae.fr/app/ShinySBM)). C'est un résumé d'application d'un modèle à blocs stochastique. La partie moélisation est basé sur le package [sbm](https://CRAN.R-project.org/package=sbm) de R.

## Données

```{r child2}
```

  - Le réseau est `r R$upload$Dataset$type`
  - Les noeuds du réseaux sont composés de `r ifelse(is_bipartite, paste(dim(R$upload$Dataset$matrix)[2],R$upload$labels$col,"en colonnes et",dim(R$upload$Dataset$matrix)[1], R$upload$labels$row,"en lignes"), paste(dim(R$upload$Dataset$matrix)[2],R$upload$labels$col))`
  - Les arêtes prennent des valeurs `r ifelse(R$upload$Dataset$law == "bernoulli","binaires (0 ou 1)",ifelse(R$upload$Dataset$law == "poisson", "enti\ue8res (0, 1, 2 , ...)","r\ue9elles"))` `r ifelse(is_bipartite,"",ifelse(R$upload$directed,"et sont dirig\ue9es.","et sont sym\ue9triques."))`



## Visualisation de la matrice
