---
title: "shinySBM report"
format: html
params:
  data: NULL
  sbm: NULL
  options: NULL
---

# Introduction

données décrites
application sbm + plus citatio

# Matrice de Reseaux

un visuel de Matrice

# SBM resultat

# Introduction

données décrites
application sbm + plus citatio

# Matrice de Reseaux

```{r}
library(shinySbm)
```



```{r}

plotSbm(params$data$Dataset$matrix, tanspose = params$options$showTransposed,
        labels = params$data$labels,plotOptions = params$options)

```

resultats pour tout les nb groups


```{r}
switch(params$options$whichMatrix,
       "raw" = plotSbm(params$sbm,
              ordered = FALSE, transpose = params$options$showTransposed,
              labels = params$data$labels,
              plotOptions = params$options
            ),
       "ordered" = plotSbm(params$sbm,
              ordered = TRUE, transpose = params$options$showTransposed,
              labels = params$data$labels,
              plotOptions = params$options
            ),
       "expected" = plotSbm(params$sbm,
              ordered = TRUE, transpose = params$options$showTransposed,
              labels = params$data$labels,
              plotOptions = c(params$options, showValues = F)
            ))  

```

résumé des valeur
Matrices (which)
reseaux simplifi



# conclusion
